### ISSUE TITLE
Create test suite for Repeat schedules

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#199] opened 2018-08-19 18:04 UTC
This is an excellent ticket for someone who wants to thoroughly learn and master Repeat schedules in ZIO. I'm happy to offer 1-on-1 support to anyone who has any questions about completing this ticket.

 - [ ] Create a new `RepeatSpec`
 - [ ] Systematically test methods of `Schedule` by using `IO.repeat`.

**Comment by randbw** [comment] 2018-09-06 20:16
I've started this :smiley:

**Comment by fanf** [comment] 2018-10-30 11:12
I've open a PR for first very simple tests on `repeat` and I'm not sure of the semantic of `repeat(Schedule.recurs(0))` as shown in the failing test.

**Comment by randbw** [comment] 2018-10-30 22:10
Hi, I was still planning on finishing this off. As stated I've begun already and am going to focus more of my spare time on this ticket now that some of my others in the scalaz-ioqueue project have been finished.

If desired I can also open a PR for what I've done so far although I was thinking to wait until it was closer to completion before I did that.

**Comment by fanf** [comment] 2018-11-01 07:49
@randbw oh sorry! During the scala.io scala-center spree, I looked for an easy, and since that one was silent since some time, I tried it. I don't need to have my PR merged :) And I'm sure that having some tests is better than no test (so yeah for a PR!), and a full test suit is even better than some test (I don't know about the convention for #zio, but perhaps it's ok to make PR so that the problem is completed iteratively - it's not always possible, but for tests, it works ok)

**Comment by fanf** [comment] 2018-11-06 09:15
OK, some more thinking on that: what should be the semantic of: 
```
for {
      ref <- Ref(0)
      _   <- ref.update(_ + 1).repeat(Schedule.once)
      res <- ref.get
    } yield res
```

- a) `res == 1` because `ref` is updated one time, and `Schedule.once` means that it should be done only one time in all ?
- b) `res == 2`, because it is updated one time, and `repeat` means that it should be executed on *additionnal* time ?

If we go for a), and if `Schedule.recurs(1)` and `Schedule.once` have the same semantic about the number of time the execution happens (notwithstanding the different return type), it leads to an inconsistancy with `repeat(Schedule.recurs(1)) means exec one additional time`
=> we need either different semantic for `recurs(1)` and `once`, or give up with the *additional* semantic (so that `recurs(1)` means "one execution in total, and so 0 additionnal".

If we go for b), we need to change the implementation of `repeat(Schedule.once)` to match the one of `repeat(Schedule.recurs(1))`.


Choice summary: 
- A/ `recurs(1)` and `once` have a different semantic for `repeat`: `repeat(...recurs(1))` means "exec one additionnal time" whereas `repeat(...once)` means "exec one time only, 0 additionnal times"
- B.1/ `recurs(1)` and `once` have the same semantic for `repeat`, and both means "repeat one additionnal time" => we need to change `once` implementation
- B.2/ `recurs(1) and `once` have the same semantic for `repeat`, and both means "exec one times in total, i.e 0 additionnal one" => we need to adapt `recurs` implementation.

What do you think? @jdegoes particulary

**Comment by fanf** [comment] 2018-11-08 15:02
Perhaps @regiskuckaertz can be interested too in above comment since you reacted on https://github.com/scalaz/scalaz-zio/pull/323

**Comment by jdegoes** [comment] 2018-11-08 16:38
I vastly prefer _B.1_ or _B.2_. I think most people would expect `retry(recurs(1))` to mean one retry (i.e. two total executions of the original action); probably most people would expect `repeat(recurs(1))` to mean one repeat (i.e. two total executions). This implies _B.1_, I think.

**Comment by regiskuckaertz** [comment] 2018-11-08 18:00
So it's
```
io.repeat(recurs(0)) = io.repeat(never) = io
io.repeat(recurs(1)) = io.repeat(once)  = io *> io
io.repeat(recurs(2))                    = io *> io *> io
io.repeat(recurs(3))                    = io *> io *> io *> io
...
```
I agree, B1, especially when you read it oud loud, "repeat io once".

**Comment by fanf** [comment] 2018-11-10 13:38
@regiskuckaertz `io.repeat(Schedule.never)` does not terminate, so the semantic is different. 

Thanks for the summary, it reads really well, I will use it :)

**Comment by fanf** [comment] 2018-11-10 13:55
I propose to deal with consistancy problem of repeat/retry for recurse/once in https://github.com/scalaz/scalaz-zio/issues/366 and keep that ticket for a more exhaustiv test framework for `repeat`.

**Comment by regiskuckaertz** [comment] 2018-11-10 16:49
That's nice:
```
io × 0 = io.repeat(never)                       = IO.never
io × 1 = io.repeat(recurs(0))                   = io
io × 2 = io.repeat(recurs(1)) = io.repeat(once) = io *> io
...
```

**Closed** 2019-04-11 19:11 UTC
Labels: good first issue, hacktoberfest
