### ISSUE TITLE
Is it a good idea to keep defect lists as separate values for all the ExitStatus branches? 

### ISSUE THREAD

**Issue by pshirshov** [scalaz/scalaz-zio#170] opened 2018-08-10 22:40 UTC
It may be nice to keep consistency and allow the user to easily distinguish between defects and causes when the evaluation terminates. I've opened a P/R for this: #169 

Also I'm curious what happens when computation succeds but bracket finalizers fail?
It seems logical to return the value computed. At the same time in case it happens user may wish to get a list of defects as well. So I think it may be a good idea to add defects list into ExitStatus.Completed as well. What do you think?

**Comment by regiskuckaertz** [comment] 2018-11-10 18:19
I think [the redesign of `ExitResult`](https://github.com/scalaz/scalaz-zio/pull/342) solves this issue?

**Comment by kaishh** [comment] 2018-11-11 17:07
Hmm, please correct me if I'm wrong, but I think we still can't tell which of the `unchecked` exceptions are the causes of termination and which of them were collected from finaliser failures ._.

**Comment by jdegoes** [comment] 2018-12-20 16:10
Fixed in the new lossless error model

**Closed by jdegoes** 2018-12-20 16:10 UTC
